# Generated by Django 3.1.1 on 2021-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Фирма')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('year_start', models.IntegerField(verbose_name='Год')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'МКПП'), (2, 'АКПП'), (3, 'Роботизированная')], verbose_name='Коробка передач')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
        ),
    ]
